### ISSUE TITLE
Connect with Chapel Hill regarding SMS/ Messaging

### ISSUE THREAD

**Issue by Olivia-Chiong** [hackforla/revenue#12]
### Overview
Code for Chapel Hill has reached out about the potential to collaborate with HfLA on creating a community resource for SMS/Messaging

### Action Items
- [x] Bonnie should reply to email and set up a meeting time to find out more.

**Comment by ExperimentsInHonesty** [comment]
Repied and discussed the following:
  - [Chapel Hill Community Resource site](https://nccovidsupport.org/)
  - [Backend Tool that the nccovidsupport.org site is built on](https://umbraco.com/pricing/)

**Comment by ExperimentsInHonesty** [comment]
No opportunity for revenue at this time.
