### ISSUE TITLE
Test Zapier connection

### ISSUE THREAD

**Issue by Civic-Opportunity-Project** [hackforla/revenue#15]
- [x] Test connection to Github repo
- [x] Test issue created when new spreadsheet row created on Recruitment Pipeline response sheet

**Comment by rjdoria** [comment]
Test successful. Zapier pilot on Fundraising Pipelines complete.

Next: 
- [ ] remove Display Sheet from Fundraising Pipelines and update formatting
- [ ] update 'Create Issue' action with proper issue formatting
- [ ] clean test responses from Response Sheet
