### ISSUE TITLE
Draft a template issue for: Fundraising Experience Profile Items

### ISSUE THREAD

**Issue by mmaecruz** [hackforla/revenue#17]
### overview
Make a list of all skills, proficiencies that a fundraising volunteer can get at Hack for LA. 

### draft items

- identifying area/keywords for your project
- identify type of funding required for project
- research institutional grant makers by subject area
- review funder for open application periods
- documenting possible funders by application method (including invitation only - for later contact).
- Identify resources available given constraints
   - 990s
-  letter of inquiry, proposal, application form
- developing an org chart for a target funder
- outreach calls
- grant writing
- grant reviewing/editing
- relationship building (documenting)of staff contacts
- creating a marketing/fundraising campaign
   - brainstorming session with team for appropriate events/vehicles
  - designing materials
  - scheduling
  - social media plan
  - budget goal
- project budgets (projections)
- common attachments
   - letter of incorporation
   - 501(c)(3) letter
   - audit
   - board roster
   - duns 
   - sams
  - Define Data and outcomes for project
   -- impact data / outcomes data collection
   - designing reporting and visualization for compliance
      - define what the measurable outcomes will be 
      - how will we measure the impact
         - history
         - over 6 months
         - over 1 year
- size of the area of impact (e.g., LA county + specific part of the pop)
  - internal data sources
  - external data sources
- size of the people inside of your area of impact you will be able to reach
- define the need (narrative)
- stats about the community the project serves
- client stories
- learning different grant platforms for submitting grants electronically (cybergrants)
   - learn to be an org admin on a distributed team
- letters of support
  - drafting LOS
  - drafting the email asking for LOS
  - following up when you don't get it in a timely way
- identifying community partners
- creating a production calendar
- project leadership bios
- additional info relevant to the project (lived experience, etc.)
- - gift processing
   - thank you letters
- Summary letter (end of year, etc.)

**Comment by mmaecruz** [comment]
- identifying area/keywords for your project
- identify type of funding required for project
- research institutional grant makers by subject area
- review funder for open application periods
- documenting possible funders by application method (including invitation only - for later contact).
- Identify resources available given constraints
   - 990s
-  letter of inquiry, proposal, application form
- developing an org chart for a target funder
- outreach calls
- grant writing
- grant reviewing/editing
- relationship building (documenting)of staff contacts
- creating a marketing/fundraising campaign
   - brainstorming session with team for appropriate events/vehicles
  - designing materials
  - scheduling
  - social media plan
  - budget goal
- project budgets (projections)
- common attachments
   - letter of incorporation
   - 501(c)(3) letter
   - audit
   - board roster
   - duns 
   - sams

**Comment by mmaecruz** [comment]
@hackforla/fundraising-write @hackforla/fundraising Hi Team, I've just finished a first draft of the **experience profile issue template**. I've drafted it via google docs and it lives in my google drive. You are welcome to add it to the hackforla fundraising folder - I don't have access there. 

[https://docs.google.com/document/d/1NPADAUA330Bkc3qZAtZgA6sA1VmNNDsz-tlMSkDxI8s/edit?usp=sharing](url)

**Comment by ExperimentsInHonesty** [comment]
Here is the issue template: 
 [New issue: Fundraiser experience profile](https://github.com/hackforla/revenue/issues/new?assignees=&labels=feature%3A+experience+profile&template=fundraiser-experience-template.md&title=Fundraiser+Experience+Profile%3A+%5BYour+Name%5D)
 [Markdown template file](https://github.com/hackforla/revenue/blob/main/.github/ISSUE_TEMPLATE/fundraiser-experience-template.md)
