### ISSUE TITLE
Create fundraising letter for Youth Justice Nav

### ISSUE THREAD

**Issue by Olivia-Chiong** [hackforla/revenue#29]
### Overview
We need to create two fundraising letters for Youth Justice Nav

### Action Items
- [ ] Letter for a specific ask from general public/email campaign - $25 gift cards for system impacted youth who we plan to interview

**Comment by mmaecruz** [comment]
@mmaecruz come up with a couple of questions to help craft the letter. Also important to have questions to ask the product team as a framework for future fundraising letters/or materials.

Alicia from UCLA - would have more information, including grant language.

**Comment by mmaecruz** [comment]
Background: Mothers of young people who have better or more knowledge, generally lead to more outcomes for children who are system-impacted. That's why educating will lead to better outcomes.

**Comment by mmaecruz** [comment]
One of the questions for future fundraising letters should center on social media and who the audience is.

**Comment by mmaecruz** [comment]
@Olivia-Chiong [https://docs.google.com/document/d/1Mq5G7s3bJGLhSyyabmh_RnaepZjHiped378L-Er2keU/edit?usp=sharing](url) Hi Olivia, I've made some good progress on the fundraising letter draft for Youth Justice Nav. I still need to include the fundraising ask at the end of the letter, but I just wanted to make sure that the style of the letter was good so far. Please let me know what you think and feel free to leave any comments or suggestions on the google doc. I'll continue to refine and format the document in the meanwhile.

**Comment by mmaecruz** [comment]
Hi @Olivia-Chiong, @ExperimentsInHonesty, I am going to close this issue since it seems like the youth justice nav letter is finished based on our recent conversation. The final draft can be found hereL: https://docs.google.com/document/d/1Mq5G7s3bJGLhSyyabmh_RnaepZjHiped378L-Er2keU/edit?usp=sharing
